services:
  portal:
    image: gonzagazx/viaserra-portal:1.0-26174995
    ports:
      - "8095:80"
    restart: unless-stopped

  manutencao:
    build: ./manutencao
    ports:
      - "7095:80"
    restart: unless-stopped